### ISSUE TITLE
ERROR 403 when downloading hg19 file

### ISSUE THREAD

**Issue by dalloliogm** [KHP-Informatics/ngseasy#2]
I activated an EC2 machine and cloned ngeasy on it. The `make all` step worked perfectly, but it stopped in the hg19 rule. It seems a permission problem of the target amazon files.

```
2015-04-24 09:32:15 (74.8 MB/s) - ‘nexterarapidcapture_exome_targetedregions_v1.2.bed’ saved [5116156/5116156]

--2015-04-24 09:32:15--  https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_b37/nexterarapidcapture_expandedexome_targetedregions.bed
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 54.231.136.244
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|54.231.136.244|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10907040 (10M) [binary/octet-stream]
Saving to: ‘nexterarapidcapture_expandedexome_targetedregions.bed’

100%[===========================================================================================================================================>] 10,907,040  63.8MB/s   in 0.2s   

2015-04-24 09:32:15 (63.8 MB/s) - ‘nexterarapidcapture_expandedexome_targetedregions.bed’ saved [10907040/10907040]

cd /home/ubuntu/ngs_projects && \
    mkdir reference_genomes_hg19 && \
    cd /home/ubuntu/ngs_projects/reference_genomes_hg19 && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/1000G_omni2.5.hg19.sites.vcf && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/1000G_omni2.5.hg19.sites.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/1000G_phase1.indels.hg19.sites.vcf && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/1000G_phase1.indels.hg19.sites.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/1000G_phase1.snps.high_confidence.hg19.sites.vcf && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/1000G_phase1.snps.high_confidence.hg19.sites.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/CEUTrio.HiSeq.WGS.b37.bestPractices.hg19.vcf && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/CEUTrio.HiSeq.WGS.b37.bestPractices.hg19.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/Genome && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/GenomeIndex && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/GenomeIndexHash && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz.tbi && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/NA12878.HiSeq.WGS.bwa.cleaned.raw.subset.hg19.sites.vcf && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/NA12878.HiSeq.WGS.bwa.cleaned.raw.subset.hg19.sites.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/NA12878.HiSeq.WGS.bwa.cleaned.raw.subset.hg19.vcf && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/NA12878.HiSeq.WGS.bwa.cleaned.raw.subset.hg19.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/NA12878.knowledgebase.snapshot.20131119.hg19.vcf && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/NA12878.knowledgebase.snapshot.20131119.hg19.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/OverflowTable && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/dbsnp_138.hg19.excluding_sites_after_129.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/dbsnp_138.hg19.recab && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/dbsnp_138.hg19.vcf && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/dbsnp_138.hg19.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/get_hg19.sh && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/get_hg19_others.sh && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/hapmap_3.3.hg19.sites.vcf && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/hapmap_3.3.hg19.sites.vcf.idx && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/hg19.genome && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/index_bowtie.sh && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/index_bwa.sh && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/index_novo.sh && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/index_snap.sh && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/index_stampy.sh && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/nohup.out && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19-bs.umfa && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.1.bt2 && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.2.bt2 && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.3.bt2 && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.4.bt2 && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.dict && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fai && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta.amb && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta.ann && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta.bwt && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta.fai && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta.fai.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta.novoindex && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta.pac && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.fasta.sa && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.rev.1.bt2 && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.rev.2.bt2 && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.sthash && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/ucsc.hg19.stidx && \
    chmod -R 777 /home/ubuntu/ngs_projects/reference_genomes_hg19/
--2015-04-24 09:32:15--  https://s3-eu-west-1.amazonaws.com/ngseasy.data/reference_genomes_hg19/
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 54.231.136.244
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|54.231.136.244|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-04-24 09:32:15 ERROR 403: Forbidden.
```

**Comment by snewhouse** [comment]
ok - nuts. 

Attempting to change permissions on s3. I am working from home and my internet is cutting out...so this may take a while...I will let you know

Ive edited makefile  to remove repeated lines in top of wget of hg19 - so merge from master pretty please and then try it again later

Best bet is to run without hg19 and give it a try

More soon

**Comment by snewhouse** [comment]
ok - give it a go now

**Comment by dalloliogm** [comment]
ok, I am running it!
I did `make all` and it is downloading again reference_genomes_b37. I'll let you know when it starts with hg19.

**Comment by snewhouse** [comment]
fingers crossed...

**Comment by dalloliogm** [comment]
The hg19 rule finished correctly! 
The two hg19 and b37 rules took about 1 hour to download everything.

Now I am getting a similar error for the testdata rule.

```
cd /home/ubuntu/ngs_projects/raw_fastq && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/ && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/NA12878D_HiSeqX_R1.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/NA12878D_HiSeqX_R2.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.150x_1.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.150x_2.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.30x_1.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.30x_2.fastq.gz && \
    chmod -R 775 /home/ubuntu/ngs_projects/raw_fastq/ && \
    cd /home/ubuntu/ngs_projects/config_files && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/ngseasy_test.config.tsv && \
    chmod -R 775 /home/ubuntu/ngs_projects/config_files/ 
--2015-04-24 11:27:07--  https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 54.231.129.33
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|54.231.129.33|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-04-24 11:27:07 ERROR 403: Forbidden.
```

**Comment by snewhouse** [comment]
sorry man... ok.... try again I  30 mins.

**Comment by snewhouse** [comment]
try now...I keep loosing connections, so not sure how things proceeding, but this should work now...I hope

**Comment by dalloliogm** [comment]
Sorry, I still get the error :-(

```
mkdir -v -p /home/ubuntu/ngs_projects && \
    mkdir -v -p /home/ubuntu/ngs_projects/raw_fastq && \
    mkdir -v -p /home/ubuntu/ngs_projects/config_files && \
    mkdir -v -p /home/ubuntu/ngs_projects/run_logs && \
    mkdir -v -p /home/ubuntu/ngseasy_logs && \
    mkdir -v -p /home/ubuntu/ngseasy_tmp
cd /home/ubuntu/ngs_projects/raw_fastq && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/ && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/NA12878D_HiSeqX_R1.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/NA12878D_HiSeqX_R2.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.150x_1.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.150x_2.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.30x_1.fastq.gz && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/illumina.100bp.pe.wex.30x_2.fastq.gz && \
    chmod -R 775 /home/ubuntu/ngs_projects/raw_fastq/ && \
    cd /home/ubuntu/ngs_projects/config_files && \
    wget https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/ngseasy_test.config.tsv && \
    chmod -R 775 /home/ubuntu/ngs_projects/config_files/ 
--2015-04-24 11:53:10--  https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 54.231.132.120
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|54.231.132.120|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-04-24 11:53:10 ERROR 403: Forbidden.
```

Luckily this should be the last rule :-)

**Comment by snewhouse** [comment]
give an hour or so with this... sorry again

**Comment by dalloliogm** [comment]
don't worry, thanks for the help! :-)

**Comment by dalloliogm** [comment]
Still getting error 403. I am trying downloading the test data from https://dnanexus-rnd.s3.amazonaws.com/NA12878-xten.html , although the transfer is much slower.

**Comment by afolarin** [comment]
Hi 
The permissions for a read only bucket are give here https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html

I've fixed this now for anonymous read-only access:

@dalloliogm do you want to retry?

**Comment by afolarin** [comment]
tested e.g. object https://s3-eu-west-1.amazonaws.com/ngseasy.data/fastq_test_data/ngseasy_test.config.tsv
seems to work via my browser

**Comment by dalloliogm** [comment]
ok, I'll try again now!

**Comment by dalloliogm** [comment]
It's working! It downloaded everything now :-)

**Comment by dalloliogm** [comment]
Just a note: all the instructions in the README assume that INSTALLDIR is /media/scratch, while by default the installation is in $(HOME). I was getting errors saying that it could not find some files, until I notice that I was giving the wrong path with -d.

**Comment by snewhouse** [comment]
Cheers and sorry for confusion. I will update ASAP
